### ISSUE TITLE
Subsequent usage in the same build fails

### ISSUE THREAD

**Issue by Otterian** [evryfs/helm-ephemeral-action#591]
Currently, the name of the Helm release is static to the build number, as defined in https://github.com/evryfs/helm-ephemeral-action/blob/master/src/main.ts#L49-L52

This makes subsequent attempts to use the action in parallel jobs (or later ones) to fail, since the release name is the same and created in the same namespace.

Suggestions:

- Append a pseudo-random number to the final release name in addition to the build number
- Append the actual job name to the final release name (What if jobs happen to have the same name for whatever reason?)
- Introduce a name parameter to the chart action (requires that users of the action actually use unique names)

**Comment by davidkarlsen** [comment]
the set (repo, workflow, job, step, run-number) should be unique for any given org.
Note however that there is maximum length for a helm release.
