### ISSUE TITLE
Cannot reach database on helm-ephemeral-action v0.2.3

### ISSUE THREAD

**Issue by saulotoledo** [evryfs/helm-ephemeral-action#727]
After upgrading from v0.2.2 to v0.2.3, the ephemeral database created using the action cannot be reached.
See, for example, build attempts at https://github.com/tietoevryfs/kyc-case-service/actions/runs/3659303654/jobs/6185491870

**Comment by davidkarlsen** [comment]
Fixed in 84b2bb6e1ae70c6a846134df66416051cb5e8cde
